#!/bin/bash
# Save user SSH public key if available.
# XXX: Obviously not suitable for downloadable images.

set -e
set -o xtrace

if [ -n "$SSH_PUBKEY" ]; then
    sudo -u stack mkdir ~stack/.ssh
    sudo -Hiu stack dd of=~stack/.ssh/authorized_keys oflag=append conv=notrunc << EOF
$SSH_PUBKEY
EOF
fi
