HeatTemplateFormatVersion: '2012-12-12'
Description: 'HEAT Template - Keystone, Glance, and Nova'
Parameters:
  KeyName: {Description: Name of an existing EC2 KeyPair
      to enable SSH access to the instances, Type: String}
  InstanceType:
    Description: Use this flavor
    Type: String
    Default: m1.large
    AllowedValues: [t1.micro, m1.small, m1.large, m1.xlarge, m2.xlarge,
      m2.2xlarge, m2.4xlarge, c1.medium, c1.xlarge, cc1.4xlarge]
    ConstraintDescription: must be a valid Flavor
  ImageGen:
    Default: ubuntu-quantal-0
    Description: Prefix used for images
    Type: String
  KeystoneDbUser:
    Default: keystone
    Description: Database User for Keystone
    Type: String
  KeystoneDbPassword:
    Default: keystone
    Description: Database Password for Keystone
    Type: String
  KeystoneDatabase:
    Default: keystone
    Description: Database for Keystone
    Type: String
Resources:
  Keystone:
    Type: AWS::EC2::Instance
    DependsOn: AllDB
    Properties:
      ImageId:
        Fn::Join:
        - ''
        - - {Ref: ImageGen}
          - -keystone
      InstanceType: {Ref: InstanceType}
      KeyName: {Ref: KeyName}
      UserData: '#cloud-config'
    Metadata:
      AWS::CloudFormation::Init:
        config:
            files:
                /tmp/init-done:
                    content: ''
                    owner: root
                    group: root
                    mode: '000644'
      OpenStack::Keystone::Database:
        Host: 
          Fn::GetAtt: [AllDB, PrivateDnsName]
        User:
          Ref: KeystoneDbUser
        Database:
          Ref: KeystoneDatabase
        Password:
          Ref: KeystoneDbPassword
      OpenStack::Keystone::Bootstrap:
        Tenants:
            Name: admin
            Users:
                Name: admin
                Password: funkytown
      OpenStack::Database::Users:
        Keystone:
          User: { Ref: KeystoneDbUser }
          Databases: [ { Ref: KeystoneDatabase } ]
          Password: { Ref: KeystoneDbPassword }
      OpenStack::ImageBuilder::Elements:
        - mysql
    Properties:
      ImageId:
        Fn::Join:
        - ''
        - - {Ref: ImageGen}
          - -mysql
      InstanceType: {Ref: InstanceType}
      KeyName: {Ref: KeyName}
      UserData: ''
Outputs:
  KeystoneURL:
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt: [Keystone, PublicIp]
        - /
    Description: URL for keystone
