#!/bin/bash
# Save user SSH public key if available.
# XXX: Obviously not suitable for downloadable images.

set -e
set -o xtrace

if [ -n "$ssh_pubkey" ]; then
    sudo -u stack mkdir ~stack/.ssh
    sudo -Hiu stack dd of=~stack/.ssh/authorized_keys oflag=append conv=notrunc << EOF
$ssh_pubkey
EOF
fi
