#!/bin/bash
#
set -eu
set -o pipefail
SCRIPT_NAME=$(basename $0)
SCRIPT_HOME=$(dirname $0)

function show_options () {
    echo "Usage: $SCRIPT_NAME [options]"
    echo
    echo "Configure the bare minimum needed to use TripleO's devtest."
    echo "This script will clone TripleO's incubator, create a simple rc file that"
    echo "sets the current directory as the root and output simple instructions for"
    echo "then using devtest."
    echo
    echo "Options:"
    echo "    -h,--help              -- this help."
    echo
    exit $1
}

TEMP=$(getopt -o h -l help -n $SCRIPT_NAME -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

# Note the quotes around `$TEMP': they are essential!
eval set -- "$TEMP"

while true ; do
    case "$1" in
        -h|--help) show_options 0;;
        --) shift ; break ;;
        *) echo "Error: unsupported option $1." ; exit 1 ;;
    esac
done

function setup_rc () {
    if [ -e "demo-rc" ]; then
        return
    fi
    cat <<-EOF > demo-rc
        export TRIPLE_ROOT=$(pwd)
        export NODE_ARCH=amd64
        EOF
}

function output_help () {
    echo "TripleO is now ready to run - do so by running:"
    echo "source ./demo-rc"
    echo "./tripleo-incubator/scripts/devtest.sh --trash-my-machine --download-images=http://192.168.122.1/images/"
}

function ensure_incubator () {
    if [ -e tripleo-incubator ]; then
        return 0
    fi
    if ! git config -l > /dev/null ; then
        # TODO(lifeless) We need multi-distro support at some point
        sudo apt-get install git
    fi
    git clone https://git.openstack.org/openstack/tripleo-incubator
}

ensure_incubator
setup_rc
output_help
