#!/bin/bash
set -eu

CPU=$1
MEM=$(( 1024 * $2 ))
# extra G to allow fuzz for partition table : flavor size and registered size
# need to be different to actual size.
DISK=$(( $3 + 1))

case $4 in
    i386) ARCH='i686' ;;
    amd64) ARCH='x86_64' ;;
    *) echo "Unsupported arch $4!" ; exit 1 ;;
esac

TOTAL=$5

# define the default storage pool if its not there yet
(virsh pool-list --all --persistent | grep -q default) || (
 virsh pool-define-as --name default dir --target /var/lib/libvirt/images; virsh pool-autostart default; virsh pool-start default)

PREALLOC=
if [ -f /etc/debian_version ]; then
  PREALLOC="--prealloc-metadata"
fi

MACS=""
for (( count=idx=0; count<TOTAL; ++idx )) ; do
  (virsh list --all | grep -q baremetal_$idx) && continue
  virsh vol-create-as default baremetal-$idx.qcow2 ${DISK}G --format qcow2 $PREALLOC >/dev/stderr
  configure-vm --bootdev network --name baremetal_$idx --image /var/lib/libvirt/images/baremetal-$idx.qcow2 --arch $ARCH --cpus $CPU --memory $MEM >/dev/stderr
  sudo chattr +C /var/lib/libvirt/images/baremetal-$idx.qcow2 || true
  get-vm-mac baremetal_$idx
  (( ++count ))
done
