#!/bin/bash
set -eu

BASE=$(dirname $0)/../

CPU=$1
MEM=$(( 1024 * $2 ))
# extra G to allow fuzz for partition table : flavor size and registered size
# need to be different to actual size.
DISK=$(( $3 + 1))

case $4 in
    i386) ARCH='i686' ;;
    amd64) ARCH='x86_64' ;;
    *) echo "Unsupported arch $4!" ; exit 1 ;;
esac

TOTAL=$5
count=0


# define the default storage pool if its not there yet
(virsh pool-list --all --persistent | grep default) || (
 virsh pool-define-as --name default dir --target /var/lib/libvirt/images; virsh pool-autostart default; virsh pool-start default)

for (( count=0; count<TOTAL; ++count )) ; do
  # TODO: make this idempotent / at least not error when run more than once.
  virsh vol-create-as default baremetal-$count.qcow2 ${DISK}G --format qcow2 --prealloc-metadata
  configure-vm --bootdev network --name baremetal_$count --image /var/lib/libvirt/images/baremetal-$count.qcow2 --arch $ARCH --cpus $CPU --memory $MEM
done
