#!/bin/bash

# If something goes wrong bail, don't continue to the end
set -e
set -o xtrace

if [ ! -e ~/devstack ]; then
    # We use devstack to bootstrap
    git clone --branch baremetal-dev git://github.com/tripleo/devstack.git
    # our localrc reflects our policy on top of devstack.
fi
cp ~/incubator/localrc ~/devstack/

# Run devstack itself:
cd ~/devstack
./stack.sh
. ./openrc

#Workaround https://bugs.launchpad.net/horizon/+bug/1070083 - (Quantal
# virtual machines only).
if [ ! -e /usr/bin/node ]; then
  sudo ln -s nodejs /usr/bin/node
fi

# Do the bits that devstack doesn't do for us
~/incubator/scripts/user-setup.sh



set +x
echo "Incubator environment ready to roll."
echo "Now source the config - 'source ~/devstack/openrc',"
echo "Add hardware nodes via ~/incubator/scripts/populate-nova-bm-db.sh -i NIC add"
echo "And boot via nova boot --flavor 11 --image demo --key_name default bmtest"

echo "You may find q-dhcp agent spewing errors (check in screen -x stack). If so, change the root-helper for it to sudo, see https://bugs.launchpad.net/quantum/+bug/1080846"
