#!/bin/bash

set -eu
set -o pipefail

[ -c /dev/kvm ] || sudo mknod /dev/kvm c 10 232
sudo chmod 666 /dev/kvm
[ -c /dev/net/tun ] || {
    sudo mkdir -p /dev/net
    sudo mknod /dev/net/tun c 10 200
}
sudo chmod 666 /dev/net/tun
for ((d=0;d<=7;d++)); do
    [ -b /dev/loop$d ] || sudo mknod /dev/loop$d b 7 $d
    sudo chmod 666 /dev/loop$d
done
[ -c /dev/loop-control ] || sudo mknod /dev/loop-control c 10 237
sudo chmod 666 /dev/loop-control
[ -c /dev/mapper/control ] || {
    sudo mkdir -p /dev/mapper/
    sudo mknod /dev/mapper/control c 10 236
}
sudo chmod 666 /dev/mapper/control
sudo service libvirtd stop
cat > /tmp/libvirtd.conf <<EOF
unix_sock_group = "libvirt"
unix_sock_ro_perms = "0777"
unix_sock_rw_perms = "0777"
unix_sock_dir = "/var/run/libvirt"
auth_unix_ro = "none"
auth_unix_rw = "none"
EOF
cat > /tmp/libvirt.conf <<EOF
uri_default = "qemu:///system"
EOF
sudo mv /tmp/libvirt*.conf /etc/libvirt
sudo service libvirtd start
