#!/bin/bash
#
# Copyright 2013 Hewlett-Packard Development Company, L.P.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

set -eu

SCRIPT_NAME=$(basename $0)
SCRIPT_HOME=$(dirname $0)


function show_options () {
    echo "Usage: $SCRIPT_NAME [options]"
    echo
    echo "Extract documentation from our demonstration scripts."
    echo
    echo "This will create devtest.rst from devtest.sh."
    echo
    echo "Options:"
    echo "    -h -- Show this help screen."
    echo
    exit 0
}

TEMP=`getopt -o h -l help -n $SCRIPT_NAME -- "$@"`
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

# Note the quotes around `$TEMP': they are essential!
eval set -- "$TEMP"

while true ; do
    case "$1" in
        -h | --help) show_options;;
        --) shift ; break ;;
        *) echo "Error: unsupported option $1." ; exit 1 ;;
    esac
done

EXTRA=${1:-""}

for script in $(ls $SCRIPT_HOME/../scripts/devtest*.sh) ; do
    bname=${script##*/}
    noext=${bname%.sh}
    # Skip devtest_functions.sh
    [ "$bname" == "devtest_functions.sh" ] && continue
    awk -f $SCRIPT_HOME/extract-docs.awk $script > $SCRIPT_HOME/../doc/source/$noext.rst
done
