#!/bin/sh
set -eu

if [ "$#" -eq 0 ]; then
  echo "provide vm name as argument."
  exit 1
fi

mac=$(sudo virsh dumpxml $1 | grep "mac address" | head -1 | awk -F "'" '{print $2}')

arp -n | grep $mac > /dev/null
if [ $? -ne 0 ]; then
  echo "mac $mac not found. it's possible that the vm just isn't up yet."
  exit 1
fi

arp -n | grep $mac | awk '{print $1}'
