#!/bin/sh
set -eu

PATH=$PATH:/usr/sbin:/sbin

if [ "$#" -lt 1 ]; then
    echo "Usage: $(basename $0) <vm-name>"
    exit 1
fi

VMNAME=$1

vms=$(sudo virsh list --all | grep $VMNAME | awk '{ print $2 }')

macs=""
for vm in $vms ; do
    macs="$(sudo virsh dumpxml $vm | grep "mac address" | head -1 | awk -F "'" '{ print $2 }') $macs"
done

echo $macs
