#!/bin/sh
set -u

PATH=$PATH:/usr/sbin:/sbin

VMNAME=${1:-""}
ip=""

if [ -z "$VMNAME" ]; then
  echo "provide vm name as argument."
  exit 1
fi

while true ; do
  echo "Looking for $VMNAME..." >&2
  mac=$(sudo virsh dumpxml $VMNAME 2>/dev/null | grep "mac address" | head -1 | awk -F "'" '{print $2}')

  if [ "$mac" != "" ]; then
    ip=$(arp -n | awk " / $mac/ {print \$1}")

    if [ -z "$ip" ] ; then
      ip=$(sudo awk "/$mac/ { print \$3 }" /var/lib/libvirt/dnsmasq/default.leases)
    fi
  fi

  if [ -z "$ip" ]; then
    echo "VM $VMNAME not found. It may not have booted yet. Waiting..." >&2
    sleep 2
    continue
  fi

  break;
done

if [ ! -z "$ip" ]; then
  echo $ip
fi
