#!/bin/bash
#
# Copyright 2013 Hewlett-Packard Development Company, L.P.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

set -eu
set -o pipefail

SCRIPT_NAME=$(basename $0)
SCRIPT_HOME=$(dirname $0)

function show_options () {
    echo "Usage: $SCRIPT_NAME [options] <service-token> <keystone-endpoint> <admin-email> <keystone-ssh>"
    echo
    echo "Perform initial setup of admin domain for Heat."
    echo
    echo "This will create a domain for Heat, an admin user for the domain,"
    echo "and add the admin user to said domain."
    echo
    echo "Options:"
    echo "    -p, --password    -- Choose the Heat Stack Domain Admin User password."
    echo
    echo "For instance: $SCRIPT_NAME -p <password>"
    exit $1
}

DOMAIN_ADMIN_PASSWORD="" # Default to making a random one.

TEMP=`getopt -o hp: -l help,password: -n $SCRIPT_NAME -- "$@"`
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

# Note the quotes around `$TEMP': they are essential!
eval set -- "$TEMP"

while true ; do
    case "$1" in
        -p | --password) DOMAIN_ADMIN_PASSWORD=$2; shift 2 ;;
        -h) show_options 0;;
        --) shift ; break ;;
        *) echo "Error: unsupported option $1." ; exit 1 ;;
    esac
done

# Heat Domain
# Note we have to pass token/endpoint here because the current endpoint and
# version negotiation in OSC means just --os-identity-api-version=3 won't work
KS_ENDPOINT_V3="http://$HOST:5000/v3"

HEAT_DOMAIN_ID=$(openstack domain create heat \
    --os-identity-api-version=3 \
    --os-url $KS_ENDPOINT_V3 \
    --os-token $OS_TOKEN \
    --description "Owns users and projects created by heat" \
    | grep ' id ' | awk '$2=="id" {print $4}')
HEAT_DOMAIN_ADMIN_USER_ID=$(openstack user create --password "$DOMAIN_ADMIN_PASSWORD" \
    --os-identity-api-version=3 \
    --os-url $KS_ENDPOINT_V3 \
    --os-token $OS_TOKEN \
    --domain $HEAT_DOMAIN_ID \
    --description "Manages users and projects created by heat" \
    heat_domain_admin \
    | grep ' id ' | awk '$2=="id" {print $4}')
openstack role add \
    --os-identity-api-version=3 \
    --os-url $KS_ENDPOINT_V3 \
    --os-token $OS_TOKEN \
    --user $HEAT_DOMAIN_ADMIN_USER_ID --domain $HEAT_DOMAIN_ID admin
