#!/bin/bash
set -eu

# keys
if ! grep "$(cat ~/.ssh/id_rsa.pub)" ~/.ssh/authorized_keys >/dev/null; then
  cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
fi

# libvirtd group
grep libvirtd /etc/group || sudo groupadd libvirtd
if ! id | grep libvirtd; then
   echo "adding $USER to group libvirtd"
   sudo usermod -a -G libvirtd $USER
   exec sudo su -l $USER $PWD/$0
   PRINT_RESTART=1
fi

# packages
sudo apt-get update
DEBIAN_FRONTEND=noninteractive sudo apt-get install --yes python-lxml python-libvirt libvirt-bin qemu-system qemu-kvm git python-pip python-dev
sudo pip install -U python-novaclient python-glanceclient python-heatclient python-keystoneclient

sudo service libvirt-bin restart

echo "Check to see that you are in the libvirtd group in your current shell before going on. You can check by running:"
echo
echo "id | grep libvirtd"
echo
echo "If you are not, it's because this script added you. You can pick up the group by logging out and back in, or run:"
echo
echo "sudo su -l $USER"
