#!/bin/bash
# generate ssh authentication keys if they don't exist
if [ ! -f /root/.ssh/id_rsa_virt_power ]; then
    ssh-keygen -t rsa -N "" -C virtual-power-key -f /root/.ssh/id_rsa_virt_power
fi

# make the local id_rsa_virt_power.pub be in ``.ssh/authorized_keys`` before
# that is copied into images via ``local-config``
if ! grep -qF "$(cat /root/.ssh/id_rsa_virt_power.pub)" /root/.ssh/authorized_keys; then
    cat /root/.ssh/id_rsa_virt_power.pub >> /root/.ssh/authorized_keys
    chmod 0600 /root/.ssh/authorized_keys
fi