#!/bin/bash
#
# Copyright 2013 Hewlett-Packard Development Company, L.P.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

set -eu

# This is a cheap mr/cm-alike. Perhaps we should use mr/cm.

TOOLS="https://git.openstack.org/openstack/diskimage-builder https://git.openstack.org/openstack/tripleo-image-elements https://git.openstack.org/openstack/tripleo-heat-templates https://git.openstack.org/openstack/tripleo-incubator"

ZUUL_REF=${ZUUL_REF:-''}

if [ -n "$ZUUL_REF" ]; then
    echo "SKIPPING pull-tools as ZUUL_REF is present."
    exit 0
fi

for TOOL in $TOOLS; do
    TOOL_BASE=$(basename $TOOL)
    echo pulling/updating $TOOL_BASE
    if [ ! -d $TRIPLEO_ROOT/$TOOL_BASE ] ; then
        cd $TRIPLEO_ROOT
        git clone $TOOL
    else
        cd $TRIPLEO_ROOT/$TOOL_BASE
        if [ "$(git symbolic-ref -q HEAD | rev | cut -d "/" -f 1 | rev || :)" = "master" ] ; then
            if ! git pull --ff-only ; then
                    echo "***************************************************"
                    echo "* Perhaps you want to 'git rebase origin/master'? *"
                    echo "***************************************************"
                    exit 1
            fi
        else
            echo "***************************************"
            echo "* Not on master branch, skipping pull *"
            echo "***************************************"
        fi
    fi
    echo -n $TRIPLEO_ROOT/$TOOL_BASE:
    cd $TRIPLEO_ROOT/$TOOL_BASE
    git --no-pager log -1 --pretty=oneline
done
