#!/bin/bash
#
# Copyright 2013-2014 Hewlett-Packard Development Company, L.P.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

__tripleo_refresh_env() {
    export TRIPLEO_ROOT=$1

    for PROJNAME in tripleo-incubator tripleo-image-elements diskimage-builder \
            tripleo-heat-templates ; do
        UPPER_PROJNAME=$(echo $PROJNAME | tr a-z A-Z)
        UPPER_PROJNAME=${UPPER_PROJNAME//[-.]/_}
        if [ -d $TRIPLEO_ROOT/openstack/$PROJNAME ] ; then
            eval $UPPER_PROJNAME=$TRIPLEO_ROOT/openstack/$PROJNAME
        else
            eval $UPPER_PROJNAME=$TRIPLEO_ROOT/PROJNAME
        fi
    done

    export PATH=$TRIPLEO_INCUBATOR/scripts:$PATH
    source $(dirname $BASH_SOURCE)/set-os-type
    export NODE_DIST=${NODE_DIST:-"$TRIPLEO_OS_DISTRO"}
    pull-tools
    setup-clienttools
    export ELEMENTS_PATH=$TRIPLEO_IMAGE_ELEMENTS/elements

    echo "Make sure to source your stackrc file"
}

# Setup/update your undercloud environment to run devtest_overcloud.sh
#
if [ -z "${1:-}" ] ; then
  echo "Usage:"
  echo "source refresh-env TRIPLEO_ROOT"
  echo "Ex:"
  echo "source refresh-env ~/tripleo"
else
  if [ -d "$1/tripleo-incubator/scripts" ] ; then
    __tripleo_refresh_env $1
  else
    echo "TRIPLEO_ROOT must contain tripleo-incubator/scripts"
  fi
fi
