#!/bin/bash
#
# Copyright 2013 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

set -e
set -o pipefail

SCRIPT_NAME=$(basename $0)
SCRIPT_HOME=$(dirname $0)

function show_options () {
    echo "Usage: $SCRIPT_NAME [-f] FILENAME [options]"
    echo
    echo "Generate passwords for devtest and write them out to a file"
    echo "that can be sourced."
    echo
    echo "Options:"
    echo "    -f, --file        -- Specify path for passwords file."
    echo "                         For backwards compatibility only;"
    echo "                         FILENAME is now mandatory."
    echo "    -o, --overwrite   -- Overwrite file if it already exists."
    exit $1
}

FILE=

TEMP=`getopt -o hof: -l help,overwrite,file: -n $SCRIPT_NAME -- "$@"`
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

# Note the quotes around `$TEMP': they are essential!
eval set -- "$TEMP"

while true ; do
    case "$1" in
        -f | --file) FILE=$2; shift 2 ;;
        -o | --overwrite) OVERWRITE=--overwrite; shift 1 ;;
        -h | --help) show_options 0;;
        --) shift ; break ;;
        *) echo "Error: unsupported option $1." ; exit 1 ;;
    esac
done

FILE=${FILE:-$1}

if [-z "$FILE" ]; then
  echo "ERROR: Must provide a filename"
  exit 1
fi

OVERWRITE=${OVERWRITE:-""}

# Don't overwrite $FILE if it already exists and the overwrite option
# wasn't provided.
if [ -f $FILE -a -z "$OVERWRITE" ]; then
    echo $FILE exists, not overwriting.
    echo Either delete the file first, or specify -o
    exit 0
fi

touch $FILE
# Make the file secure as reasonably possible.
chmod 0600 $FILE

cat > $FILE << EOF
UNDERCLOUD_ADMIN_TOKEN=$(os-make-password)
UNDERCLOUD_ADMIN_PASSWORD=$(os-make-password)
UNDERCLOUD_GLANCE_PASSWORD=$(os-make-password)
UNDERCLOUD_HEAT_PASSWORD=$(os-make-password)
UNDERCLOUD_NEUTRON_PASSWORD=$(os-make-password)
UNDERCLOUD_NOVA_PASSWORD=$(os-make-password)
UNDERCLOUD_IRONIC_PASSWORD=$(os-make-password)
EOF
