#!/bin/bash
#
# Copyright 2013 Hewlett-Packard Development Company, L.P.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

set -eu

SCRIPT_NAME=$(basename $0)
SCRIPT_HOME=$(dirname $0)

function show_options () {
    echo "Usage: $SCRIPT_NAME [options] <controlplane-ip>"
    echo
    echo "Perform initial setup of a cloud running on <controlplane-ip>"
    echo
    echo "This will register ec2, image, orchestration, identity, network, and"
    echo "compute services as running on the default ports on controlplane-ip."
    echo
    echo "Options:"
    echo "    -r, --region      -- Override the default region 'regionOne'."
    echo
    echo "For instance: $SCRIPT_NAME 192.0.2.1"
    exit 0
}

REGION="regionOne" #NB: This is the keystone default.

TEMP=`getopt -o r: -l region: -n $SCRIPT_NAME -- "$@"`
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

# Note the quotes around `$TEMP': they are essential!
eval set -- "$TEMP"

while true ; do
    case "$1" in
        -r) export REGION=$2; shift 2 ;;
        --region) export REGION=$2; shift 2 ;;
        -h) show_options;;
        --) shift ; break ;;
        *) echo "Error: unsupported option $1." ; exit 1 ;;
    esac
done

HOST=${1:-""}
EXTRA=${2:-""}

if [ -z "HOST" -o -n "$EXTRA" ]; then
    show_options
fi

export PASSWORD=unset
SERVICE_ENDPOINT=http://$HOST:35357/v2.0 register-endpoint -r $REGION -d "Keystone Identity Service" keystone identity http://$HOST:5000 -a http://$HOST:35357
unset SERVICE_TOKEN
register-endpoint -r $REGION -d "Heat Service" heat orchestration http://$HOST:8004
register-endpoint -r $REGION -d "Neutron Service" neutron network http://$HOST:9696
register-endpoint -r $REGION -d "Glance Image Service" glance image http://$HOST:9292
register-endpoint -r $REGION -d "EC2 Compatibility Layer" ec2 ec2 http://$HOST:8773
register-endpoint -r $REGION -d "Nova Compute Service" nova compute http://$HOST:8774
