#!/bin/bash
set -eu

BASE=$(dirname $0)/../

# Only add brbm if missing
(sudo ovs-vsctl list-br | grep brbm) || sudo ovs-vsctl add-br brbm

# remove brbm before replacing it.
(virsh net-list --all --persistent | grep brbm) && (
 virsh net-destroy brbm; virsh net-undefine brbm)
virsh net-define $BASE/templates/brbm.xml
virsh net-start brbm
