#!/bin/bash
#
# Copyright 2013-2014 Hewlett-Packard Development Company, L.P.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

set -eu
set -o pipefail

SCRIPT_NAME=$(basename $0)
SCRIPT_HOME=$(dirname $0)

function show_options () {
    echo "Usage: $SCRIPT_NAME [options]"
    echo
    echo "Reads a JSON file describing machines for a baremetal cluster and"
    echo "registers them all with Nova baremetal. Excess machines are removed"
    echo "and flavors are created to match the machines that have been"
    echo "registered using the local deploy-ramdisk and kernel, which are also"
    echo "loaded into glance."
    echo
    echo "Options:"
    echo "      -h             -- this help"
    echo "      --service-host -- nova bm service host to register nodes with"
    echo "      --nodes        -- JSON list of nodes to register"
    echo "      --flavors      -- JSON list of flavors to register"
    echo
    exit $1
}

SERVICE_HOST=""
NODES_PATH=
FLAVORS_PATH=

TEMP=$(getopt -o h -l help,service-host:,nodes:,flavors: -n $SCRIPT_NAME -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

# Note the quotes around `$TEMP': they are essential!
eval set -- "$TEMP"

while true ; do
    case "$1" in
        -h | --help) show_options 0;;
        --service-host) SERVICE_HOST="$2"; shift 2 ;;
        --nodes) NODES_PATH="$2"; shift 2 ;;
        --flavors) FLAVORS_PATH="$2"; shift 2 ;;
        --) shift ; break ;;
        *) echo "Error: unsupported option $1." ; exit 1 ;;
    esac
done

if [ -z "$SERVICE_HOST" ]; then
    echo "Ironic not supported, please specify --service-host."
    exit 1
fi
if [ -z "$JSON_PATH" ]; then
    echo "A node list is required."
    exit 1
fi

NODES=$(cat $NODES_PATH)
register-nodes -s $SERVICE_HOST -n <(echo $NODES)

if [ $USE_IRONIC -eq 0 ]; then
    deploy_base=deploy-ramdisk
else
    deploy_base=deploy-ramdisk-ironic
fi

deploy_kernel=$TRIPLEO_ROOT/$deploy_base.kernel
deploy_ramdisk=$TRIPLEO_ROOT/$deploy_base.initramfs
deploy_kernel_id=$(glance image-create --name bm-deploy-kernel --public \
    --disk-format aki < "$deploy_kernel" | awk ' / id / {print $4}')
deploy_ramdisk_id=$(glance image-create --name bm-deploy-ramdisk --public \
    --disk-format ari < "$deploy_ramdisk" | awk ' / id / {print $4}')

# If no flavors specified, use the details of the first node instead and
# call it "baremetal"
if [[ -z "${FLAVORS_PATH}" ]]; then
    flavors=$(jq -r '{"baremetal": .[0]}' <<< ${NODES})
else
    flavors=$(cat ${FLAVORS_PATH})
fi

flavors=$(jq -r 'map(.ephemeral=.disk - '${ROOT_DISK}' |
                     .deploy_kernel_id='"${deploy_kernel_id}"' |
                     .deploy_ramdisk_id='"${deploy_ramdisk_id}"')' <<< $flavors)

register-flavors --teardown --flavors <(echo $flavors) --nodes "${NODES_PATH}"

