#!/bin/bash
#
# Copyright 2013 Red Hat, Inc.
# Copyright 2013 Hewlett-Packard Development Company, L.P.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

set -e
set -o pipefail

SCRIPT_NAME=$(basename $0)
SCRIPT_HOME=$(dirname $0)

function show_options () {
    echo "Usage: $SCRIPT_NAME [options]"
    echo
    echo "Generate passwords for devtest and write them out to a file"
    echo "that can be sourced."
    echo
    echo "Options:"
    echo "    -f, --file        -- Specify path for passwords file."
    echo "                         Defaults to tripleo-undercloud-passwords,
                                     or tripleo-overcloud-passwords if -c with
                                     OVERCLOUD specified, in the current
                                     directory."
    echo "    -c, --cloud       -- Specify UNDERCLOUD or OVERCLOUD."
    echo "                           Defaults is UNDERCLOUD."
    echo "    -o, --overwrite   -- Overwrite file if it already exists."
    exit $1
}

TEMP=`getopt -o hof:c: -l help,overwrite,file,cloud: -n $SCRIPT_NAME -- "$@"`
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

# Note the quotes around `$TEMP': they are essential!
eval set -- "$TEMP"

while true ; do
    case "$1" in
        -f | --file) FILE=$2; shift 2 ;;
        -c | --cloud) CLOUD=$2; shift 2 ;;
        -o | --overwrite) OVERWRITE=--overwrite; shift 1 ;;
        -h) show_options 0;;
        --) shift ; break ;;
        *) echo "Error: unsupported option $1." ; exit 1 ;;
    esac
done

CLOUD=${CLOUD:-"UNDERCLOUD"}
FILE=${FILE:-"tripleo-${CLOUD,,}-passwords"}
OVERWRITE=${OVERWRITE:-""}

# Don't overwrite $FILE if it already exists and the overwrite option
# wasn't provided.
if [ -f $FILE -a -z "$OVERWRITE" ]
then
    echo $FILE exists, not overwriting.
    echo Either delete the file first, or specify -o
    exit 0
fi

touch $FILE
# Make the file secure as reasonably possible.
chmod 0600 $FILE

cat > $FILE << EOF
${CLOUD}_ADMIN_TOKEN=$(os-make-password)
${CLOUD}_ADMIN_PASSWORD=$(os-make-password)
${CLOUD}_CINDER_PASSWORD=$(os-make-password)
${CLOUD}_GLANCE_PASSWORD=$(os-make-password)
${CLOUD}_HEAT_PASSWORD=$(os-make-password)
${CLOUD}_NEUTRON_PASSWORD=$(os-make-password)
${CLOUD}_NOVA_PASSWORD=$(os-make-password)
${CLOUD}_SWIFT_PASSWORD=$(os-make-password)
${CLOUD}_SWIFT_HASH=$(os-make-password)

${CLOUD}_DEMO_PASSWORD=$(os-make-password)
EOF
