#!/bin/bash
#
# Copyright 2013 Hewlett-Packard Development Company, L.P.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

set -eu

SCRIPT_NAME=$(basename $0)
SCRIPT_HOME=$(dirname $0)

function show_options () {
    echo "Usage: $SCRIPT_NAME [options] <controlplane-ip>"
    echo
    echo "Perform initial setup of a cloud running on <controlplane-ip>"
    echo
    echo "This will register ec2, image, orchestration, identity, network, "
    echo "volume (optional), dashboard (optional), metering (optional) and "
    echo "compute services as running on the default ports on controlplane-ip."
    echo
    echo "Options:"
    echo "    -r, --region            -- Override the default region 'regionOne'."
    echo "    --ceilometer-password   -- Specify a password for ceilometer"
    echo "    --cinder-password       -- Specify a password for cinder."
    echo "    --glance-password       -- Specify a password for glance."
    echo "    --heat-password         -- Specify a password for heat."
    echo "    --ironic-password       -- Specify a password for ironic."
    echo "    --neutron-password      -- Specify a password for neutron."
    echo "    --nova-password         -- Specify a password for nova."
    echo "    --swift-password        -- Specify a password for swift"
    echo "    --enable-horizon        -- Enable horizon"
    echo "    --debug                 -- Debug the API calls made."
    echo
    echo "For instance: $SCRIPT_NAME 192.0.2.1"
    exit $1
}

DEBUG=""
CEILOMETER_PASSWORD=""
CINDER_PASSWORD=""
GLANCE_PASSWORD=""
HEAT_PASSWORD=""
IRONIC_PASSWORD=""
NEUTRON_PASSWORD=""
NOVA_PASSWORD=""
SWIFT_PASSWORD=""
ENABLE_HORIZON=""
REGION="regionOne" #NB: This is the keystone default.

TEMP=`getopt -o r: -l region:,debug,ceilometer-password:,cinder-password:,glance-password:,heat-password:,ironic-password:,neutron-password:,nova-password:,swift-password:,enable-horizon -n $SCRIPT_NAME -- "$@"`
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

# Note the quotes around `$TEMP': they are essential!
eval set -- "$TEMP"

while true ; do
    case "$1" in
        -r|--region) export REGION=$2; shift 2 ;;
        --debug) export DEBUG=--debug; shift 1;;
        --ceilometer-password) export CEILOMETER_PASSWORD=$2; shift 2 ;;
        --cinder-password) export CINDER_PASSWORD=$2; shift 2 ;;
        --glance-password) export GLANCE_PASSWORD=$2; shift 2 ;;
        --heat-password) export HEAT_PASSWORD=$2; shift 2 ;;
        --ironic-password) export IRONIC_PASSWORD=$2; shift 2 ;;
        --neutron-password) export NEUTRON_PASSWORD=$2; shift 2 ;;
        --nova-password) export NOVA_PASSWORD=$2; shift 2 ;;
        --swift-password) export SWIFT_PASSWORD=$2; shift 2 ;;
        --enable-horizon) export ENABLE_HORIZON=--enable-horizon; shift 1;;
        -h) show_options 0;;
        --) shift ; break ;;
        *) echo "Error: unsupported option $1." ; exit 1 ;;
    esac
done

HOST=${1:-""}
EXTRA=${2:-""}

if [ -z "$HOST" -o -n "$EXTRA" ]; then
    show_options 1
fi

PASSWORD=$IRONIC_PASSWORD register-endpoint $DEBUG -r $REGION -d "Ironic Service" ironic baremetal http://$HOST:6385
PASSWORD=$HEAT_PASSWORD register-endpoint $DEBUG -r $REGION -d "Heat Service" heat orchestration http://$HOST:8004
PASSWORD=$NEUTRON_PASSWORD register-endpoint $DEBUG -r $REGION -d "Neutron Service" neutron network http://$HOST:9696
PASSWORD=$GLANCE_PASSWORD register-endpoint $DEBUG -r $REGION -d "Glance Image Service" glance image http://$HOST:9292
register-endpoint $DEBUG -r $REGION -d "EC2 Compatibility Layer" ec2 ec2 http://$HOST:8773
PASSWORD=$NOVA_PASSWORD register-endpoint $DEBUG -r $REGION -d "Nova Compute Service" nova compute http://$HOST:8774
PASSWORD=$NOVA_PASSWORD register-endpoint $DEBUG -r $REGION -d "Nova Compute Service v3" nova computev3 http://$HOST:8774
if [ -n "$CEILOMETER_PASSWORD" ]; then
  PASSWORD=$CEILOMETER_PASSWORD register-endpoint $DEBUG -r $REGION -d "Ceilometer Service" ceilometer metering http://$HOST:8777
fi
if [ -n "$CINDER_PASSWORD" ]; then
  PASSWORD=$CINDER_PASSWORD register-endpoint $DEBUG -r $REGION -d "Cinder Volume Service" cinder volume http://$HOST:8776
fi
if [ -n "$SWIFT_PASSWORD" ]; then
  PASSWORD=$SWIFT_PASSWORD register-endpoint $DEBUG -r $REGION -d "Swift Object Storage Service" swift object-store http://$HOST:8080
fi
if [ -n "$ENABLE_HORIZON" ]; then
    register-endpoint $DEBUG -r $REGION -d "OpenStack Dashboard" horizon dashboard http://$HOST
fi
