#!/bin/bash
#
# Copyright 2013 Hewlett-Packard Development Company, L.P.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

set -eu

STACK_NAME=${1:-''}

if [ -z "$STACK_NAME" ]; then
    echo "No stack name supplied" >&2
    exit 1
fi

STACK_STATUS=$(heat stack-show $STACK_NAME | awk '/ stack_status / { print $4 }')

if [ "CREATE_COMPLETE" = "$STACK_STATUS" -o "UPDATE_COMPLETE" = "$STACK_STATUS" ]; then
    exit 0
elif [ "CREATE_FAILED" = "$STACK_STATUS" ]; then
    # The stack will never be ready so notify the wait_for command of this
    echo "The stack has failed to start and will never be ready."
    echo "STACK_STATUS=$STACK_STATUS"
    exit 2
else
    exit 1
fi
