#!/bin/bash

set -e
set -u
set -x

SCRIPT_NAME=$(basename $0)

LOOPS=${1:-""}
SLEEPTIME=${2:-""}
STACK_NAME=${3:-""}
if [ -z "$LOOPS" -o -z "$SLEEPTIME" -o -z "$STACK_NAME" ]; then
    echo "Usage: $SCRIPT_NAME LOOPS_NUMBER SLEEP_TIME STACK_NAME"
    exit 1
fi

SUCCESSFUL_MATCH_OUTPUT="(CREATE|UPDATE)_COMPLETE"
FAIL_MATCH_OUTPUT="CREATE_FAILED"

SUCCESSFUL_MATCH_OUTPUT=$SUCCESSFUL_MATCH_OUTPUT \
    FAIL_MATCH_OUTPUT=$FAIL_MATCH_OUTPUT \
    wait_for $1 $2 \
        "heat stack-show $STACK_NAME | awk '/stack_status / { print \$4 }'"
