#!/bin/bash
#
# Copyright 2015 Hewlett-Packard Development Company, L.P.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

set -eu

SCRIPT_NAME=$(basename $0)

TIMEOUT=${1:-""}
DELAY=${2:-""}
STACK_NAME=${3:-""}
if [ -z "$TIMEOUT" -o -z "$DELAY" -o -z "$STACK_NAME" ]; then
    echo "Usage: $SCRIPT_NAME TIMEOUT DELAY STACK_NAME"
    exit 1
fi

SUCCESSFUL_MATCH_OUTPUT="(CREATE|UPDATE)_COMPLETE"
FAIL_MATCH_OUTPUT="(CREATE|UPDATE)_FAILED"

SUCCESSFUL_MATCH_OUTPUT=$SUCCESSFUL_MATCH_OUTPUT \
    FAIL_MATCH_OUTPUT=$FAIL_MATCH_OUTPUT \
    wait_for_walltime $1 $2 \
        "heat stack-show $STACK_NAME | awk '/stack_status / { print \$4 }'"
